name: Build and Deploy Frontend on GitHub Pages
on: 
  push:
    branches:
	  - "deploy-github-pages"
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        working-directory: ./app/ui
		run: |
          npm install
          npm ci
          npm run build

      - name: Deploy 🚀
		working-directory: ./app/ui
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.